#name: Deploy BigQuery View
#
#on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'flight_booking_view.sql' #hope it gets success
#
#  pull_request:
#    branches:
#      - main
#    paths:
#      - 'flight_booking_view.sql'
#
#  workflow_dispatch:
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Authenticate to Google Cloud
#        uses: google-github-actions/auth@v1
#        with:
#          # Service account key JSON, stored as a repo secret
#          credentials_json: ${{ secrets.GCP_SA_KEY }}
#
#      - name: Set up gcloud & gsutil
#        uses: google-github-actions/setup-gcloud@v2
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          # optional: install components
#          install_components: gsutil
#
#      - name: Run bq to deploy view
#        run: |
#          bq query \
#            --use_legacy_sql=false \
#            --project_id=${{ secrets.GCP_PROJECT_ID }} \
#            < flight_booking_view.sql
#
#
name: Deploy BigQuery View in QA and Prod

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'flight_booking_view.sql' #hope it gets success

  pull_request:
    branches:
      - main
    paths:
      - 'flight_booking_view.sql'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          # Service account key JSON, stored as a repo secret
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud & gsutil
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          # optional: install components
          install_components: gsutil

      - name: Deploy View to QA
        if: github.ref == 'refs/heads/dev'
        run: |
          bq query \
            --use_legacy_sql=false \
            --project_id=${{ secrets.GCP_PROJECT_ID }} \
            --destination_table=timmu_test.flight_booking_view \
            < flight_booking_view.sql

      - name: Deploy View to PROD
        if: github.ref == 'refs/heads/main'
        run: |
          bq query \
            --use_legacy_sql=false \
            --project_id=${{ secrets.GCP_PROJECT_ID }} \
            --destination_table=timmu_test_prod.flight_booking_view \
            < flight_booking_view.sql